# Site settings
title: Qwer999 - lazylog
email: qwer999@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.qwer999.net" # the base hostname & protocol for your site
twitter_username: qwer999
github_username:  qwer999

# Plugin
gems: 	["emoji_for_jekyll", "jekyll-auto-image"]

# Build settings
markdown: kramdown

permalink:  /:title